### ISSUE TITLE
SSL: Could not be Parsed

### ISSUE THREAD

**Issue by ASPI259** [dani-garcia/bitwarden_rs#1002]
Hi,

i followed this guide: https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome
and createt the Certificates in the Dictionary: /var/lib/docker/volumes/ssl
This i passed through to the Container but i cant start the container.
Log shows: .... could not be parsed...

any tips?

**Comment by ASPI259** [comment]
Exact Log: 
Logger failed to initialize: attempted to set a logger after the logging system was already initialized


[2020-05-21 19:35:45][rocket::config::error][ERROR] environment variable ROCKET_TLS={certs="/ssl/bitwarden/bitwarden.crt",key="/ssl/bitwarden/bitwarden.key" could not be parsed

ROCKET_TLS='{certs="/ssl/bitwarden/bitwarden.crt",key="/ssl/bitwarden/bitwarden.key"}'

Volume:

/var/lib/docker/volumes/ssl:/ssl

**Comment by Link009** [comment]
Take a look here: https://lucians.dev/solve-bitwardenrs-this-subtle-is-null-error

Is bitwarden.crt formatted corectly ? Also, what are you trying to achieve ? Enable SSL or create a self signed certificate ?

The link I posted is for the first issue.

**Comment by drkeni9ma** [comment]
> /var/lib/docker/volumes/ssl

Did you create it in your docker container? If so, I suggest you create your cert and key files in the host machine

<host:container>

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to continue this discussion on the forum: https://bitwardenrs.discourse.group/

We suggest to use a reverse-proxy for ssl-offloading, because reverse proxy are better in handling SSL.
Also checkout some of the updated/new wiki articles:
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs
https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome

**Comment by vszakats** [comment]
Had this error when trying to use an ECC certificate. It's a misleading message as the setting was correctly formatted and the files were in their correct location. Replacing them with RSA keys made the error go away.
