### ISSUE TITLE
ios app connection doesn't work

### ISSUE THREAD

**Issue by Ghost108** [dani-garcia/bitwarden_rs#1073]
Hello :),

I can access the web interface via: http://IP_SYNOLOGY:3373
I would only access bitwarden locally.
I road that bitwarden requires https - this I solved with synology reverse proxy.

The web interface is now accessable via: https://SYNOLOGY_DSM_NAME:3373
(login and bitwarden works !)

With the windows and macOS client I can access my bitwarden server.
For this I use the server address https://SYNOLOGY_DSM_NAME:3373 angegeben.

But with the ios App I get this error:

An error has occurred.
Exception message: An SSL error has occurred. A secure connection to the server cannot be established.

Any idea?

**Comment by dani-garcia** [comment]
Is the certificate self-signed or is it a valid one for that domain?

**Comment by Ghost108** [comment]
it is self-signed , created by the synology assistent

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to continue this discussion on the forum: https://bitwardenrs.discourse.group/

We suggest to use a reverse-proxy for ssl-offloading, because reverse proxy are better in handling SSL.

Also checkout some of the updated/new wiki articles:
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs
https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome
