### ISSUE TITLE
iPhone, manjaro bitwarden-desktop ssl issue

### ISSUE THREAD

**Issue by feydreva** [dani-garcia/bitwarden_rs#1132]
Hello, 
I am having issue with ssl.

I have a bitwarden docker installed on an ubuntu server vm, in my lan network, not accessible from outside. (I use home wifi, home ethernet, or a vpn to access it)
Before ssl, everything worked almost fine, my iPhone could connect, my manjaro bitwarden-desktop app could connect, firefox app could connect. 
The only thing that did not work was connecting to the web interface from firefox, because ssl certificates are needed.
I wanted to access from the web interface, so I could get to the more advance option, like Organization and security reports.

So I installed sll following 
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS 
and
https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome

So now I have home made certificates and bitwarden configured for it.
I can now access bitwarden from the web interface (after cleraing security warning about my certificates being not secure) and have now access to all the functionality.
The Firefox extension stil connects
But my iPhone app, and the manjaro bitwarden-deskop app cannot connect.
In iPhone, I get a ssl error, and in the desktop app, i get a fetch error.

What should I do to solve theses issue ?
Thank you for your help

**Comment by dani-garcia** [comment]
I think iPhone doesn't allow self signed certificates by default, you might need to look how to add self signed certificates to the iPhones trust store.

**Comment by setBoolean** [comment]
You could the use wildcard certs from:

https://github.com/hjmmc/xip-dns-server
https://xip.lhjmmc.cn/

**Comment by BlackDex** [comment]
Closing this ticket because of inactivity.
Feel free to continue this discussion on the forum: https://bitwardenrs.discourse.group/

We suggest to use a reverse-proxy for ssl-offloading, because reverse proxy are better in handling SSL.
Also checkout some of the updated/new wiki articles:
https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-HTTPS
https://github.com/dani-garcia/bitwarden_rs/wiki/Running-a-private-bitwarden_rs-instance-with-Let%27s-Encrypt-certs
https://github.com/dani-garcia/bitwarden_rs/wiki/Private-CA-and-self-signed-certs-that-work-with-Chrome
