### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by Yazur-admin** [dani-garcia/bitwarden_rs#1192]
Hello,

My server bitwarden_rs works very well in HTTPS.
On the other hand when I enter the same URL in HTTP I get "ERR_EMPTY_RESPONSE" a blank page with "this page doesn't work".

I tried to add -p 80:80 to my docker file but it doesn't work.
I can access the site at https://.... :80
While I would like to have port 80 for http not https x)...

Thanks in advance.

**Comment by AtjonTV** [comment]
`While I would like to have port 80 for http not https` may I ask if you plan to copy your passwords over unencrypted HTTP?

Anyways, I would recommend using a Reverse Proxy like Caddy. It manages Lets Encrypt Certs for your and lets you redirect http to https. You would then have HTTP traffic between Bitwarden and the Proxy but its on the same server anyways so there are no high risks, as long as your SSH access is secure and up to date.

I have been using bitwarden_rs behind Caddy since I switched from KeePass about a year ago, I never had issues with http redirects.

**Comment by Yazur-admin** [comment]
Thank you for the answer.

We already use Pfsense to manage traffic from the internet.
And on this Pfsense is the ACME package with Lets Encrypt by which our TLS certificate is distributed on the bitwarden server.

I don't want to be able to use HTTP, I just want the bitwarden server to listen to the http port and redirect it to the HTTPS port.

Just like a simple web server with a redirect in the virtual host.

But I have the impression that the server refuses any request for the url starting with HTTP.

**Comment by mqus** [comment]
Afaik this is right, because bitwarden_rs only ever listens to one port, either with tls or without. For advanced features like http redirect you'll need a reverse proxy like caddy, nginx or apache.

**Comment by wcjxixi** [comment]
if you use Nginx -- https://phoenixnap.com/kb/redirect-http-to-https-nginx

or like me, just insert `return 301 https://$server_name$request_uri;` to `/usr/local/nginx/conf/vhost/mybitwarden.com.conf` file.

like this:
`server
    {
        listen 80;
        #listen [::]:80;
        server_name mybitwarden.com ;
        index index.html index.htm index.php default.html default.htm default.php;
        root  /home/wwwroot/mybitwarden.com;

        return 301 https://$server_name$request_uri;

        include rewrite/none.conf;
        #error_page   404   /404.html;

        # Deny access to PHP files in specific directory
        #location ~ /(wp-content|uploads|wp-includes|images)/.*\.php$ { deny all; }

        include enable-php.conf;
`

**Comment by BlackDex** [comment]
Closing this issue since this is not something we can fix.
Please use a reverse-proxy to handle these cases.
