### ISSUE TITLE
Feature request: LDAP Backend

### ISSUE THREAD

**Issue by ImNtReal** [dani-garcia/bitwarden_rs#122]
It would be awesome if I could integrate this with my existing LDAP server, so my account to get my master password would be the same that I use to login to the rest of the services I'm hosting on the same server.

**Comment by dani-garcia** [comment]
I think this is in the same position as #94, if someone can PR an implementation that isn't overly complex, I'll be happy to merge it, but I don't plan on doing this myself.

**Comment by dani-garcia** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246.

**Comment by dani-garcia** [comment]
Huh, I didn't know that the directory connector existed, I though that was integrated in the server. I would prefer to keep compatible with the official server yes. 

In this case, the connector probably makes LDAP easier to implement, but how does it work exactly? Does that create the users or do they need to exist already? Is the functionality just adding and removing users from the org or is there more?

Groups at the moment are not implemented, only collections, so that's something to have in mind, but we could have a version that only handles users.

I imagine an implementation of this would be similar to the methods `send_invite`, `confirm_invite` and  `delete_user` that we already have to handle adding and removing users from organizations. This is in `src/api/core/organizations.rs`.

**Comment by MrSnoozles** [comment]
I think it *should* create and delete the users too, as one of the point of LDAP/ Active Directory is, that you set up users only once for all your applications. I'm going to try it with the official server and let you know.

**Comment by dani-garcia** [comment]
That would make sense, but the data sent doesn't contain a passwordhash or anything and we need that to create the account, so if it works like that then the login step has to be different.

**Comment by MrSnoozles** [comment]
It's just adding and removing people to/from the organization depending on the email address. They have to exist in the system before and are not getting created.

**Comment by ViViDboarder** [comment]
FYI: A form of LDAP syncing has been [added to the wiki](https://github.com/dani-garcia/bitwarden_rs/wiki/Syncing-users-from-LDAP).
