### ISSUE TITLE
Cannot disable password hint

### ISSUE THREAD

**Issue by ronaldr1987** [dani-garcia/bitwarden_rs#1228]
### Subject of the issue
Cannot disable password hint

### Your environment
Bitwarden_rs version: 2.16.1
Docker + portainer on ubuntu 20.0.0.4
SMTP + 2FA enabled as environment variable.

### Steps to reproduce
Added SHOW_PASSWORD_HINT=false as environment variable.

### Expected behaviour
Password hint to be disabled on main page.

### Actual behaviour
Password hint is still on main page and not disabled.

**Comment by BlackDex** [comment]
The password hint button is not something we (can) remove since this is built in into the web-vault.
We do however prevent this function from working if you have configured that setting.
If you have that setting set to true it will show a green popup on the right side which includes your password hint.

**Comment by ronaldr1987** [comment]
I have set this to false but still working

**Comment by BlackDex** [comment]
Please read #945 .
This was asked and answered before.
