### ISSUE TITLE
Is the new Personal Ownership function available in RS?

### ISSUE THREAD

**Issue by yurividal** [dani-garcia/bitwarden_rs#1319]
https://bitwarden.com/help/article/policies/#personal-ownership

Is this already available in Bitwarden_RS?

**Comment by BlackDex** [comment]
Short answer, no (not yet).

Longer answer. If someone has time and the will to add this feature they are free to do so and create a PR to add this feature.

**Comment by yurividal** [comment]
Thanks @BlackDex .
I just wish this was not "low priority"... it's a pretty useful feature for admins to be able to restrict users from saving passwords to a personal vault, and always default passwords to the team.

**Comment by BlackDex** [comment]
Well i put it to low since it's not something which breaks currently working features. And there are other issues which i think do need more attention.

Btw, same goes for the emergency access feature, that is very useful for personal usage.

Also, maybe for larger organizations, it could be better to use the official version, since that has more features then we have at the moment. Like groups and auditing logs, etc..
