### ISSUE TITLE
Latest docker image has still version 1

### ISSUE THREAD

**Issue by Haxy89** [dani-garcia/bitwarden_rs#149]
I use image from https://hub.docker.com/r/mprasil/bitwarden/tags/ with lastest tag.
Web interface is old, not the newest 2.2.0

**Comment by mprasil** [comment]
You must be running some older image, I've literary just pulled and launched the container and it's bundled with 2.1.1 version of Vault. (the latest released)

**Comment by mprasil** [comment]
Just to add, you can see [latest buid log here](https://hub.docker.com/r/mprasil/bitwarden/builds/bv3tvsdrgpdo2xkqzk9wxxp/). It clearly builds 2.1.1 Vault. Try to run `docker pull mprasil/bitwarden` before running your container.

**Comment by dani-garcia** [comment]
Version 2.2 is still not released according to 
https://github.com/bitwarden/web/releases
We’ll wait until an official release before bumping the included version.

**Comment by Haxy89** [comment]
Sorry all for my mistake. I use Portainer to manage my docker containers and it did not pull the newest image when I create new container.

So I use the newest one 2.1.1 but have problem with web interface response time, it is slower than version 1. 

Do someone has the same problem?

**Comment by mprasil** [comment]
What do you mean by slower @Haxy89 ? Like generally navigating ciphers, searching and so on, or something that hits server like saving changes, moving between folders and the like?

I can't really say I've noticed any slowness, but it's generally javascript heavy application and I can see how it can be slower on less powerful PCs.

**Comment by Haxy89** [comment]
@mprasil 
Displaying login page tooks 30seconds, login to main view took 10-20seconds. Before update to 2.1.1 everythings worked faster

**Comment by mprasil** [comment]
That sounds like some javascript related issue. Did you try to check in the developer tools in browser on the network tab how the requests get through? The login screen loads for me in about a second, so this indeed sound slow but not really related to server changes.

The initial load after login can be affected by server changes (due to slow sync) but there were no major changes server-side between V1 and V2 so it sounds unlikely. How many passwords do you have stored?
