### ISSUE TITLE
Can't add new Item or Collection to Organization

### ISSUE THREAD

**Issue by biztems** [dani-garcia/bitwarden_rs#267]
Hi,
I can't add anything to an Organization - adding an Item and clicking on the "Save" button just does nothing. I don't even get any error message in the logs. I can't rename the default organization either (EDIT: logged error added).

I also get the same issues from issue #261 if I try adding a new organization - same exact behaviour.

This happens on both the latest master and 1.4.0. I even tried 1.3.0 and I just get the same issues.

Any help please? Without Organizations Bitwarden is pretty much useless to us :disappointed: 

If there's anything I can do to help, please let me know.
Thanks!

EDIT:
Here's what the log spouts out when trying to rename the default Organization (this is on a self-built from master):

    PUT /api/organizations/00000000-0000-0000-0000-000000000000 application/json; charset=utf-8:
    => Matched: PUT /api/organizations/<org_id>
    ERROR: Failed to modify organization
    => Outcome: Success
    => Response succeeded.

I also get this almost every page reload:

    GET /undefined:
    => Matched: GET /<p..>
    => Error: Response was a non-`Responder` `Err`: Os { code: 2, kind: NotFound, message: "No such file or directory" }.
    => Outcome: Failure
    => Warning: Responding with 404 Not Found catcher.
    => Response succeeded.```

**Comment by dani-garcia** [comment]
What web vault version are you using?

**Comment by biztems** [comment]
> What web vault version are you using?

Hi, it's version 2.5.0 on the self-built master I'm using currently. The same happens even when using the docker versions, though - which from what I gather should have older, stable Vaults directly embedded into them.

**Comment by mprasil** [comment]
@biztems, please read again the [warning](https://github.com/dani-garcia/bitwarden_rs#configure-server-administrator) before enabling `SERVER_ADMIN_EMAIL`. You're trying to use the virtual organization as normal organization. This will not work. You're also trying to use `SERVER_ADMIN_EMAIL` as normal user for other tasks, this too won't work. Use a separate user for server administration and everything should work well.

Hope that helps.

I'm going to close this as I'm pretty sure this is your issue here, but if you still have issues after following mu advice, feel free to reopen or submit new issue.

Also if you have any advice how to make the warning more visible to users, please let me know, we had couple users tripped on this already, I tried to make the warning more explicit, but some users still get confused, so hopefully there's a way to improve the situation.

**Comment by biztems** [comment]
> Also if you have any advice how to make the warning more visible to users, please let me know, we had couple users tripped on this already, I tried to make the warning more explicit, but some users still get confused, so hopefully there's a way to improve the situation.

Welp, you're right. Must've overlooked it!

By the way, to make it more visible... err, I know it kinda looks unprofessional, but maybe emojis are the way? Something like ⚠️ should work.

**Comment by mprasil** [comment]
Emoji to the rescue. 😄 I was thinking about renaming the setting variable to something that would make it a bit more explicit, that the admin user will be broken for all purposes other than server admin, but I couldn't come up with name that wouldn't be crazy long like: `BREAK_USER_WITH_THIS_EMAIL_AND MAKE_THEM_SERVER_ADMIN`

**Comment by biztems** [comment]
> Emoji to the rescue.  I was thinking about renaming the setting variable to something that would make it a bit more explicit, that the admin user will be broken for all purposes other than server admin, but I couldn't come up with name that wouldn't be crazy long like: `BREAK_USER_WITH_THIS_EMAIL_AND_MAKE_THEM_SERVER_ADMIN`

Heh! Maybe something like `ADMIN_USER_HACK` - the word "hack" would probably make everyone think twice before enabling it :smile:  Anyway, thanks again to you and the others working on this for all your efforts - everything's working wonderfully now.
