### ISSUE TITLE
Mobile app fails to sync when user is in organizations with multiple collections

### ISSUE THREAD

**Issue by aksdb** [dani-garcia/bitwarden_rs#313]
#### Description
I managed to setup a user that can no longer sync. The user is in an organization where he is only associated to one of two collections but has admin rights. Therefore he is still allowed to see all collections. The end result is, that the mobile app crashes immediately (right after sync and then right upon startup).
In a debug session on Android I found that the exception is apparently a duplicate key while creating the dictionary for the Collections the user can see. Indeed, one collection UUID is in there twice.

#### Root cause
From what I can tell, the root of that evil is in `collections.rs`: `find_by_user_uuid`. The result of that function is a vector containing the *sum* of two queries, therefore having the same UUID (possibly) twice in the resultset.

#### Solution
Either cleanup beforehand or use a `HashSet` instead of a `Vec`  (I didn't want to simply change that, since my Rust knowledge is rudimentary and you may have a good reason to use a `Vec` instead of a 
`HashSet`).

#### Remarks
I'm not sure why the .NET dictionary mapping is so fragile regarding duplicate keys, but I think the proper solution here is to not send duplicate keys in the first place.

**Comment by dani-garcia** [comment]
I'm not sure why that's happening, those two queries do two independent things:
- The first one returns all the collections that the user has access_all enabled for (These shouldn't have entries in users_collections)
- The second one returns the entries in users_collections, for the cases where the user only has access to specific collections.

If there are duplicate entries, that must mean the user has the access_all field set to true, but also has entries in users_collections, which doesn't make sense, because when access_all is true, those users_collections are not created.

If you go to the organization from the web vault, edit the user that is giving you problems, make sure that the access all collections is checked and click save, does the problem still happen?

But anyway, I think the cleanest solution would be to change the second query to check that access_all is equal to false, then there should be no possibility of overlap.

**Comment by mprasil** [comment]
I think @aksdb was implying that the user gets access to collection twice via direct collection assignment and via the admin privileges that inherently give access to all collections. However I can't reproduce the described behaviour of `/api/sync` that only returns assigned collections either directly or via access all.

**Comment by aksdb** [comment]
Strange. The user had individual collections and also the allow_all flag set. Changing anything in the web ui did not clear the allow_all flag. I now did that manually.
Now the problem seems to be a slightly different one, because apparently one cipher in the collection returns the same collection UUID twice in the JSON response. I will try to clean that up as well.
So I think the problem is not as generic as I thought at first.... either I have a data corruption due to version updates or there is a race condition somewhere. I will try to reproduce it with a clean DB.

**Comment by mprasil** [comment]
I've created a PR, that changes the function for fetching collections. Can you compile my branch and see if that fixes the sync?

**Comment by aksdb** [comment]
@mprasil The PR seems to remedy my initial problem. Cool!
One thing that it does differently from before (afaics) is that someone with role admin can still be restricted in collections he can see. I do actually find that better though, since the (admin) user can then still edit himself if he wants to see more collections. It's even cool that the admin can now restrict the items he sees.
Since I'm not running the official Bitwarden server, I cannot compare how that one handles it (ok, I could of course check the source code .... ) but I think it's not necessary for bitwarden_rs to behave exactly the same as the official server anyway.

My other problem still persists though, and I have not yet figured out how to reproduce it on a clean DB.

```json
{
  "Ciphers": [
    {
      "Attachments": [],
      "CollectionIds": [
        "e1697705-11c0-45ad-a9c0-49d136a1807b",
        "e1697705-11c0-45ad-a9c0-49d136a1807b"
      ],
....
```
I think the only cause for this could be within the JOINs ... but since all join conditions are on the UUIDs, that doesn't make much sense. But I keep investigating :-)

**Comment by aksdb** [comment]
Ok I found it. I'll fork, patch and open a PR.
