### ISSUE TITLE
Dockerfile for building the web vault

### ISSUE THREAD

**Issue by hb3b** [dani-garcia/bitwarden_rs#334]
I've tried to build the web vault unsuccessfully using the latest "ubuntu" and "node" images on Docker Hub. Would it be possible to add a Dockerfile to that repository w/ the build steps?

Log: https://gist.github.com/hb3b/a2aea345abeb1ccc51bed77c9a14b59a

**Comment by dani-garcia** [comment]
That's weird, if you clone https://github.com/bitwarden/web and then do:
```
npm install
npm run dist
```

Does that work fine?

**Comment by mprasil** [comment]
Considering we do not directly build Vault for the official images anymore, wouldn't it make more sense to move the build instructions (and this issue) to the [other project](https://github.com/dani-garcia/bw_web_builds)?

**Comment by dani-garcia** [comment]
I think it makes sense to keep them here, because anyone building the web vault is doing so to use it with this project, so at least to me it makes sense to keep it all together in one place.

The biggest reason there is a separate repo is mostly because we are already using the releases page for the bitwarden_rs releases and I didn't want to mix and match.

About this issue, I wouldn't mind making a builder image, but I'm not sure how to make it so the compiled vault is moved to the host, and not just kept inside the image, where it would be useless.

**Comment by dani-garcia** [comment]
The web vault is now building with a dockerfile so this can be closed
