### ISSUE TITLE
Error saving cipher

### ISSUE THREAD

**Issue by romain1206** [dani-garcia/bitwarden_rs#383]
[2019-02-04 22:45:47][bitwarden_rs::db::models::user][WARN] Failed to update revision for xxxxxxxx@xxxx.fr
[2019-02-04 22:45:47][bitwarden_rs::error][ERROR] Error saving cipher.
[CAUSE] DatabaseError(
    __Unknown,
    "database is locked"
)

**Comment by dani-garcia** [comment]
Can you give us some steps to reproduce the error?

**Comment by romain1206** [comment]
hello,

i have this error when i want move 300 login to another folder.

**Comment by mprasil** [comment]
I was thinking that maybe we could defer the revision update and try to compact multiple revision updates into one, but some of the vault functionality actually relies on revision being updated instantly.

I think we can attempt to retry when updating the revision rather than failing straight away. I'll try to implement that.

**Comment by mprasil** [comment]
Okay, I've created a PR, that should hopefully fix this. The revision update should now retry 10 times instead of failing instantly. (similar to attachment updates) I've tried to move about 500 items (as much as Vault let me) and it seems to handle that fine.

**Comment by dani-garcia** [comment]
This hopefully has been fixed with the latest PR. We'll have to wait an hour or so until the docker images are built.

**Comment by suricloud** [comment]
Hi,just installed,and getting this same error?
