### ISSUE TITLE
Docker run error

### ISSUE THREAD

**Issue by kjarrard** [dani-garcia/bitwarden_rs#397]
1 - Installed Ubuntu
2 - installed Docker
3 - Pulled docker image
4 - Ran  sudo docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 mprasil/bitwarden:latest

this was the error I received (sorry if this is obvious, I'm pretty new to linux):
bitwarden_admin@LIASWARDEN:~$ sudo docker run -d --name bitwarden -v /bw-data/:/data/ -p 80:80 mprasil/bitwarden:latest
6e9c5352a793230be4b1ff43d7ca36ab7c3b281e7c1e6de6ae31cf5be995874c
docker: Error response from daemon: error while creating mount source path '/bw-data': mkdir /bw-data: read-only file system.

**Comment by BlackDex** [comment]
Docker wanted to create the path /bw-data, but wasn't allowed to do so because of rights or the / filesystem is a read-only file system for some reason.
What happens if you try to create that folder your self?
```sudo mkdir /bw-data```
Does that generate an error also?
If not, what happens when you do the ```docker run``` again after creating the folder?
