### ISSUE TITLE
[Question] LTS & how are Bitwarden updates handled?

### ISSUE THREAD

**Issue by advename** [dani-garcia/bitwarden_rs#441]
I'm thinking about implementing this rust version for our company because all our servers use ZFS as system partition (not supported by official Bitwarden) and changing to Ext4 is currently not an option.

I'm wondering how the is the LTS looking for this project? And how are bitwarden updates handled? Do they need to be manually implemented into this project or are updates non dependant from Bitwarden_rs?

**Comment by dani-garcia** [comment]
We don't offer any long term support guaranteees because I don't have the bandwidth to maintain multiple versions, but I try to keep compatibility in mind and make sure that the upgrade path from one version to the next is as simple as possible, so it should be easy to keep up to date using the latest release.

We don't have automatic server updates or any kind of update notifications, but you can subscribe to the GitHub releases to be kept up-to-date.

As far as the client updates, most of them don't have breaking changes, so they should work without any modifications. If they add any new functionality or they change some API calls, then there is a chance that it would require a server update to work. This doesn't happen very often, and I try to keep up with the upstream changes to make sure that the project isn't left too far behind, but it's not perfect.

**Comment by mprasil** [comment]
I think this was answered and can be closed now. Feel free to reopen if you have further questions regarding this.
