### ISSUE TITLE
U2F not working on Chrome 75

### ISSUE THREAD

**Issue by n1am** [dani-garcia/bitwarden_rs#476]
Hi,
I'm running bitwarden_rs on docker behind an nginx proxy, using the same nginx configuration posted in the wiki.

I'm having trouble registering my U2F keys on Chrome (version 74 and 75-dev). During che registration process I get this error:
`listening for key...
Fetch finished loading: POST "https://mydomain.ltd/api/two-factor/get-u2f-challenge".
u2f.js:628 Extension JS API Version:  1.1
two-factor-u2f.component.ts:138 error: 2`

Using Firefox (with u2f support enabled) the registration and login process works fine. I used Firefox 66.0.4 and Firefox ESR 60.6.2.

Best regards
Andrea

**Comment by dani-garcia** [comment]
Did you configure the DOMAIN env variable to be equal to the URL used to access the service? Like `https://mydomain.ltd`.

Error 2 is usually a mismatched URL.

**Comment by n1am** [comment]
Hi, 
thanks for the quick reply.
The DOMAIN env variable is equal to the URL and the app-id.json presents the right URL.

I've encountered the problem only on Chrome. Using Firefox the auth process using U2F does not result in any error. I tried on different PC, with the latest Chrome stable and Dev version, unfortunately the issue persist. So I'm thinking that the problem is Chrome since it works fine on Firefox.

**Comment by algernon** [comment]
I'm seeing the same issue with Chrome 74 on Linux. My keys work fine under Firefox, but for some odd reason, it fails in Chrome.

**Comment by allgoewer** [comment]
I am having the same problem with chrome 74 (windows) but also firefox 66 (linux).
Console output is the same as @n1am is getting.

My app-id.json looks like this:
```
$ curl https://bw.llgoewer.de/app-id.json | jq '.'
{
  "trustedFacets": [
    {
      "ids": [
        "https://bw.llgoewer.de",
        "ios:bundle-id:com.8bit.bitwarden",
        "android:apk-key-hash:dUGFzUzf3lmHSLBDBIv+WaFyZMI"
      ],
      "version": {
        "major": 1,
        "minor": 0
      }
    }
  ]
}
```

**Comment by kuruptedfiend** [comment]
I am also seeing this issue with Chrome 74.  Keys work fine in Firefox, previously worked in Chrome.

**Comment by dani-garcia** [comment]
So I tried registering a key just now and the errorCode 2 seems to be caused by an encoding issue:
![image](https://user-images.githubusercontent.com/725423/57644403-53b23480-75bc-11e9-9596-1a509459a525.png)
Chrome expects base64url while we send normal base64, I think.

Also not sure if related, as I couldn't look into it, but gitea is also having problems with U2F and Chrome 74, which makes me think there was a recent change in Chrome breaking this:
https://github.com/go-gitea/gitea/issues/6748

**Comment by allgoewer** [comment]
This is the corresponding [chromium-commit](https://github.com/chromium/chromium/commit/ceb92979d1f3a77146ed68f8484636ce63073625) which forces challenged to be base64-websafe encoded.

u2f-rs encodes the challenge as base64, [see this line](https://github.com/wisespace-io/u2f-rs/blob/50626547653da4a2e3fe7b4b4e7703d4fc5267ec/src/protocol.rs#L49)

**Comment by dani-garcia** [comment]
I've updated the u2f crate to use base64url with no padding in all cases, and switched it in a commit right now, and that seems to solve the issue for me. 

For anyone wanting to test it, you can compile the master branch of the project yourselves or wait a couple of hours until the docker images are built.

After some more users confirm the fix works I'll send a PR to the official u2f repo, instead of using the fork.

**Comment by n1am** [comment]
Hi,
just tested the latest build. Problem solved.

Thanks

**Comment by allgoewer** [comment]
It seems to also be working for me, Chrome and Firefox.
