### ISSUE TITLE
Get version info?

### ISSUE THREAD

**Issue by nirvdrum** [dani-garcia/bitwarden_rs#477]
Is there any way for me to determine which version of the server I'm running? I was hoping to see which parts of the changelog are relevant to me.

I've attached a shell to a running Docker container and ran `bitwarden_rs --help` and `bitwarden_rs --version`, but both tried to start a new server process up. That failed because I'm already running an instance. But even the startup output didn't indicate the version info. I'm not sure what else to try, other than installing `strings` and running that over the binary.

**Comment by mprasil** [comment]
The server should log version on start and also should show version in admin interface.

**Comment by nirvdrum** [comment]
Okay, I see that now. It appears to be a somewhat recent addition and the build I was using predates the change. I'm curious if there was a way to get that info in older builds, but that point will be moot once I upgrade.

**Comment by mprasil** [comment]
I think you could maybe try to correlate the image hash with the build. Or maybe correlate the build date. I'm not sure if docker hub provides enough information to do that.

Generally speaking you either always want to be on the latest or at least the latest versioned release. Otherwise you might run into compatibility issues with the upstream clients.

**Comment by nirvdrum** [comment]
That's fine. But I don't like to just blindly update things. And I legitimately wanted to know what was new. The changelog is nicely formatted, but I couldn't figure out the starting point. That shouldn't be an issue going forward.
