### ISSUE TITLE
Exporting data from bitwarden

### ISSUE THREAD

**Issue by SpyTec** [dani-garcia/bitwarden_rs#504]
Hey there,

Is there a way to export keys and data? I don't want to be locked in if I choose to use this.

**Comment by dani-garcia** [comment]
You can export the user data as JSON from the web vault, would that be enough?

**Comment by SpyTec** [comment]
Is that in a format which would be easy to import back into KeePass for instance?

**Comment by dani-garcia** [comment]
I'm not sure, you'll have to check if KeePass import has an option for Bitwarden JSON (I imagine they would, it's not a complicated format, but you'll have to check).

There's also a CSV export in the web vault, which should be compatible with pretty much anything, but I think that option misses some fields, which is why the JSON option was created.

**Comment by SpyTec** [comment]
Alright. Will need to spin up an instance first to test then. A quick search for KeePass 2.0 does mention it has import functionality for Bitwarden. But I couldn't find anything suggesting it has JSON support, only txt and CSV support.

If this is possible it would be very easy for people to switch to this, as it would not make you vendor lock-in with Bitwarden and this unofficial project.

I'll let you know whether or not this is working with JSON or CSV. If it doesn't work all too well I will suggest this as a feature request

**Comment by mprasil** [comment]
Note, that server doesn't have access to the passwords as they are encrypted client-side. So I'm not sure we can provide any form of export really.

There's apparently [support for Bitwarden json import](https://sourceforge.net/p/keepass/discussion/329221/thread/c991d58564/#a760) in KeePass now, so I think we can close this now. But feel free to reopen if you think there's anything more we can do for you here. (but again, not much we can do server side due to how the encryption works)

**Comment by SpyTec** [comment]
Right yeah, if it doesn't work I feel like my ticket would be better suited for their system instead of here.

Thanks for the response both of you
