### ISSUE TITLE
MySQL images for Alpine and ARM devices not building correctly

### ISSUE THREAD

**Issue by linuxbandit** [dani-garcia/bitwarden_rs#530]
Hey all,

I run successfully `bitwardenrs/server:latest`. I wanted to add MySQL and went on trying `bitwardenrs/server-mysql:latest` and `bitwardenrs/server-mysql:alpine`, to no avail.

The errors are `"standard_init_linux.go:207: exec user process caused "no such file or directory"` in the case of alpine, and in the other case I can't gather much because my log is truncated. I will try to find better log, but meanwhile in the case of `alpine` it seems that something was possibly renamed and forgot to update all the occurences

Thank you

**Comment by linuxbandit** [comment]
Hi, never program at night...

After hitting send, I realised I do centralise my logs. Checking, it seems that non-alpine version fails complaining about the format of `DATABASE_URL`, which is correct in its form. However I am passing the environment not through command line, like in your example, but within a docker-compose file. What fixed it, therefore, was to remove the `'` surrounding the string, e.g. 
```
bitwarden:
  ...
  environment:
    - ...
    - DATABASE_URL=mysql://bitwarden:password@maria-bitwarden/bitwarden
    - NOT_WORKING='mysql://bitwarden:password@maria-bitwarden/bitwarden'
    - ...
```

So my open issue is only about the alpine version not working

Yours,
F

**Comment by mprasil** [comment]
I think the Alpine version might have issues with statically linking the mysql libs. I think this might be the similar as to why the arm builds fail.

This needs more investigation, any input how to resolve this is welcome. Meanwhile I'm going to delete Alpine image from hub.

**Comment by dcardellino** [comment]
Is there any update on building Images with MySQL/PostgreSQL Support on ARM? I am not able to build an image.

**Comment by mumrau** [comment]
@mprasil I think this issue clearly lost its traction ! (Sorry for tagging, but sometime for resurrection you need to mention people, I hope you're still the guy needed here!)

Nonetheless I do believe it would be great to help out people working on arm, especially with new Raspberry 4 which is just... an extremely decent device for a selfhosted stack.
The issues referenced used to propose ways for building on different archs, but the `Dockerfile` evolved since then and their workarounds look irrelevant nowadays.
Maybe just explanations about how to build it on your own hardware could help?

**Comment by BlackDex** [comment]
The Alpine images are a bit hard to compile right now because of some Diesel-rs compilation issues.
Mostly regarding MySQL and PostgreSQL.

We did however fixed the Debian-based builds to support all the database types. They are a bit bigger but they do work.
For Alpine (musl) builds we need to dig a bit deeper into the compilation issues.
