### ISSUE TITLE
Configured email disable enable resets email settings.

### ISSUE THREAD

**Issue by mannp** [dani-garcia/bitwarden_rs#587]
Previously working email seems to now be causing me problems.

Issue is, why reset the whole email config when selecting disable/enable?

I would have expected my existing settings to remain but just be disabled.

Or a warning to a user that their current settings will be lost, so save them elsewhere :)

**Comment by dani-garcia** [comment]
Now that you mention it yeah it doesn't make much sense to delete the disabled fields I'm not sure why I chose to do that. We could change that easy but we'll also need to make sure that the settings respect the master toggle, I'm pretty sure the mail settings do, but others like the yubico and duo might not.

**Comment by mannp** [comment]
I am sure there was a good reason at the time for that approach :)

Not entirely sure what the master toggle is and I don't use yubico or duo yet, but can understand why you want consistency.

**Comment by lorenzschmid** [comment]
Could you please elaborate on which settings exactly changed and how one can revert this?

I'm not sure if my issue is related but since recently I receive the error message "Error building email. invalid email address" when trying to log in. This happens even on previously working (and still active) accounts. Even the admin account is affected.

**Comment by mannp** [comment]
All settings get deleted when you.toggle enable / disable.

**Comment by lorenzschmid** [comment]
Thanks for the quick reply. Which settings do you mean? And which toggle are you talking about?

**Comment by mannp** [comment]
Admin panel /admin.. email settings has an option to enable or disable all your email settings.

**Comment by lorenzschmid** [comment]
Thanks a lot. I guess in this case my issue is not related.

**Comment by dani-garcia** [comment]
@mannp In the latest commit, disabling the toggle won't delete the existing values anymore.

@lorenzschmid If you are receving that error while logging in, it's because we can't send the new device login email because apparently the mail library doesn't think the email format is valid, does the email address have any weird characters? You can make the server ignore any errors sending the login email seting `REQUIRE_DEVICE_EMAIL=true`

**Comment by vverst** [comment]
>  You can make the server ignore any errors sending the login email seting REQUIRE_DEVICE_EMAIL=true

I think `REQUIRE_DEVICE_EMAIL=false` will ignore any email errors while logging in which is the default. Unless I've made a mistake somewhere.
- https://github.com/dani-garcia/bitwarden_rs/blob/c07c9995eacda130382a65910bd661551849c2fa/src/api/identity.rs#L107
- https://github.com/dani-garcia/bitwarden_rs/blob/e3404dd3222ba703d9810d585f161c06f6cb6fc7/src/config.rs#L277

**Comment by dani-garcia** [comment]
Oops yeah my mistake, edited the comment.

**Comment by mannp** [comment]
Thanks @dani-garcia for the quick fix :)

Is REQUIRE_DEVICE_EMAIL=false default as I don't specifically set it and disabling email allowed me to login again, as well as removing 2FA too.... I didn't change REQUIRE_DEVICE_EMAIL at all.

**Comment by MagicFab** [comment]
Has this been fixed in the current version ?

**Comment by dani-garcia** [comment]
This should be fixed yes.
