### ISSUE TITLE
Can you tell me the minimum hardware require for this software?

### ISSUE THREAD

**Issue by fxzxmicah** [dani-garcia/bitwarden_rs#645]
In addition, is there a non-docker installation and usage method?

**Comment by lamka02sk** [comment]
Unlike the official image, this implementation can run on basically anything. The official image requires around 1.5GB of free RAM instead of currently 16.5MB being used on my server. It is also much much faster with really close-to-zero CPU usage. 

About docker. I think it is a very convenient way to run _anything_. You don't need the newest docker version and the one included in your distro repositories will be fine. It should also be easy if you don't have any prior docker knowledge. (I am actually not sure if you can run this without docker).

When you setup docker and bitwarden, consider using nginx as reverse proxy which will allow you to enable HTTPS. If you need anything, I can post some nginx configuration and stuff.

**Comment by BlackDex** [comment]
I have mine running docker within an LXD container.
And that container is using ~360MB Of memory in total (so including services etc..)
bitwarden_rs it self is just using something around 12MB and the docker services somewhere around the 85MB.

So i would say, minimum would be somewhere near the following:
CPU: 1 core
MEM: 512MB
DISK: 3GB (Docker can use a lot of disk space, remind to cleanup old images).

**Comment by fxzxmicah** [comment]
OK，thanks @lamka02sk @BlackDex

**Comment by mqus** [comment]
For your second question, yes you absolutely can run bitwarden_rs without a docker image. I do it on a raspberry pi 3b+ and it currently needs ~10mb of RAM, and a very tiny amount of compute power.
The hard disk consumption is ca 36mb for the binary and the vault web interface and in my case the saved passwords amount to 2-3mb (single user, ~200 passwords)

For some linux systems you can find an already [packaged edition of bitwarden_rs](https://github.com/dani-garcia/bitwarden_rs/wiki/Available-packages) but you can also [build it yourself](https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary).

**Comment by mprasil** [comment]
I think question was answered so we can close this. Feel free to reopen if more information is needed.
