### ISSUE TITLE
Wiki "starting a container" is not really "starting" it

### ISSUE THREAD

**Issue by My1** [dani-garcia/bitwarden_rs#651]
https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container

it's more like creating it (run is like worst naming ever).
as a docker first user it's probably happening that people try to `run` after a stop just to crash into a conflict (like me yesterday) I think it might be wiser to not only have the run aka create part, but also how to just start it (like after a stop)

**Comment by My1** [comment]
I know the wiki is open but I thought it might be best to ask first before doing stuff and messing stuff up in ways the author did not intend.

I probably would take the starting a container page and expand it to explain the run thing.

calling it "running" a container isnt really intuitive either, since that naming is part of what makes this so confusing since run and start are usually synonymous in PC as in execute/do something, not making it obvious that the opposite of run is not stop but rm.

**Comment by mprasil** [comment]
I think it's important to clearly explain at the top of the page how to get the container running so that people can use it with one line. So I'd keep that on top.

But then we can explain what that means, etc.. I don't want this to serve as docker documentation - it should be strictly related to bitwarden_rs and link to docker docs when necessary.

So as long as there's one line to get started on top, and then max one page of explanation I'm fine with that. Any more detailed topics can be pushed to separate page.

Hope that makes sense.

**Comment by My1** [comment]
exactly that was the idea. although the thing for me was just that when using this and wanted to start the container again after a reboot I went into the conflict because well as said worst naming ever, so obviously we should have both things in place for creating and starting the container

**Comment by mprasil** [comment]
Feel free to make changes and post here if you want feedback. Thanks a lot.

**Comment by My1** [comment]
already did after posting the last reply, lol
https://github.com/dani-garcia/bitwarden_rs/wiki/Starting-a-Container

**Comment by mprasil** [comment]
Ah that's clear enough I think. Thanks for the input and improvement.
