### ISSUE TITLE
Profile picture Support

### ISSUE THREAD

**Issue by BobWs** [dani-garcia/bitwarden_rs#661]
Hi everybody,

Wouldn’t it be nice if we could upload a profile picture?
I was thinking about a private picture.

It would give users a more personal and user-friendly experience by replacing the 2 capital letters by default.
It would be useful as well to manage organisation and shared folders in order to recognize faster who are users.

I agree it’s not the most important feature for a password manager :wink:

Cheers

**Comment by BlackDex** [comment]
This would be a feature request for the upstream bitwarden project i think.
There is nothing server-side for this as far as i know.

**Comment by BlackDex** [comment]
Except for enabling gravatar support within the webvault.
But that is all client-side.

**Comment by dani-garcia** [comment]
Yeah, the clients should support gravatar, so if your email is registered in gravatar it should show the icon in the clients, note that you need to opt in for that option in each client, and you might need to log out and log back in for it to show.

**Comment by BobWs** [comment]
I would prefer personal pictures and not the gravatar support.

**Comment by mprasil** [comment]
Yeah, as @BlackDex said, this is something that should probably be requested in upstream. That was sort of requested [here](https://community.bitwarden.com/t/profile-picture-support/3884), but maybe you can raise a new request to have some local alternative to Gravatar?

I'm closing the issue here as there is nothing we can do about it right now. But if upstream decides to implement some profile picture support, we can certainly extend the API to support it.
