### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by g-acciai-sintraconsulting** [dani-garcia/bitwarden_rs#714]
Greetings,
after setting up the bitwarden_re docker and conducting some tests I noticed that in the Web App the FullText filters does not seems to work.
Wildcards does not works, nor search into custom fields or into the collection name.

Is this a planned feature to be added?

regards,

**Comment by BlackDex** [comment]
Everything regarding the web-interface, or any other client interface, is handled by the upstream project https://github.com/bitwarden/web/ .
bitwarden_rs is just a third-party server implementation.

Also, the server can't search through the stored items, this would be bad also since that would indicate the data is not stored encrypted. All is done client side.

**Comment by g-acciai-sintraconsulting** [comment]
I see, thanks for the clarification
