### ISSUE TITLE
web-vault patch doesn't work with v2.12.0

### ISSUE THREAD

**Issue by pdarcos** [dani-garcia/bitwarden_rs#774]
As the title says, I'm following the wiki and there's no v2.12.0 patch available, so I tried using the available v2.11.0.patch but git doesn't like it.

:~/web-vault# git apply v2.11.0.patch 
error: unrecognized input

Does the patch need updating to be compatible with current v.2.12.0?

**Comment by manofthepeace** [comment]
It works fine with latest web vault code;

cd code/bitwarden/web  (This is the official "web" repo of bitwarden)
git apply ../bw_web_builds/patches/v2.11.0.patch  (dani-garcia's repo)

Otherwise you can just use the prebuilt vault from here; https://github.com/bitwarden/web/releases/tag/v2.12.0 then you dont need to patch and build yourself.

**Comment by pdarcos** [comment]
Sorry. Silly mistake.
Working fine indeed
