### ISSUE TITLE
More global domains

### ISSUE THREAD

**Issue by Dubz** [dani-garcia/bitwarden_rs#811]
I'm not sure if the list used is purely from Bitwarden and should be referred to them, or if you keep this maintained separately. If it's strictly Bitwarden's list, let me know and I can send the list to them.

Here is a list of some equivalent domains that I know of.

I put them in similar format to the file, but will let one of the maintainers fill in the type value. Not sure if it's just incremental or has any sort of meaning. Also no idea what the excluded key is for, but I see all of the ones added are false so I just made all of these false as well. Do with what you'd like.
```json
  {
    "Type": ,
    "Domains": [
      "x10hosting.com",
      "x10premium.com"
    ],
    "Excluded": false
  },
  {
    "Type": ,
    "Domains": [
      "3docean.net",
      "audiojungle.net",
      "codecanyon.net",
      "envato.com",
      "graphicriver.net",
      "photodune.net",
      "themeforest.net",
      "videohive.net"
    ],
    "Excluded": false
  },
  {
    "Type": ,
    "Domains": [
      "dnsomatic.com",
      "opendns.com",
      "umbrella.com"
    ],
    "Excluded": false
  },
  {
    "Type": ,
    "Domains": [
      "cedarfair.com",
      "cedarpoint.com"
    ],
    "Excluded": false
  },
  {
    "Type": ,
    "Domains": [
      "ubnt.com",
      "ui.com"
    ],
    "Excluded": false
  }
```

Also note that these domains could be added to the group for Microsoft:
```
azure.com
microsoft365.com
office.com
```

**Comment by dani-garcia** [comment]
These are pulled from upstream yes, it's basically a dump of what the API would return, that's why the excluded is there, cause the API also returns that. The official source is in the bitwarden server project, in these two files:

https://github.com/bitwarden/server/blob/master/src/Core/Enums/GlobalEquivalentDomainsType.cs
https://github.com/bitwarden/server/blob/master/src/Core/Utilities/StaticStore.cs

You can see an example of an added change in this random PR:
https://github.com/bitwarden/server/pull/600/files#diff-08ae25c4b5138a3fc580dc436f5b74fc

**Comment by Dubz** [comment]
Gotcha, I'll go ahead and redo the list and send it to them then.
Thanks!
