### ISSUE TITLE
[Not an issue] Add a donation link

### ISSUE THREAD

**Issue by velazcod** [dani-garcia/bitwarden_rs#859]
I'd like to donate for this project but I cannot become a full on monthly supporter.

Maybe add some link like a paypal account to send money to?

Thanks a lot for your work on this, so much more efficient than the official implementation.

**Comment by meepoSenpai** [comment]
Can just second this. Also it's way easier to set up imho.

**Comment by dani-garcia** [comment]
So far I've only used github sponsors because it doesn't have any fees and github would match any contributions for the first year, but you are right that only allowing subscriptions is a bit limited.

You could always subscribe and then inmediately cancel but I can see how that can be bothersome, so maybe I should also include my paypal account there?
Link: [paypal.me/DaniGG](https://paypal.me/DaniGG)

**Comment by velazcod** [comment]
Thanks Daniel, I sent a donation to your paypal account.

**Comment by dzmitry-lahoda** [comment]
Would donate 15 USD in any crypto, and 29 in DOT (polkadot) if there will be keys.
