### ISSUE TITLE
Impossible to delete user if it is the only owner of an organization

### ISSUE THREAD

**Issue by spudjb** [dani-garcia/bitwarden_rs#936]
### Subject of the issue
If a user exists who created an organization that they are the only owner of, it is impossible to delete them.

### Your environment

* Bitwarden_rs version: 1.14.1-5471088e

* Install method: Docker image
* Clients used: admin page
* Reverse proxy and version: 
* Version of mysql/postgresql: 
* Other relevant information: 

### Steps to reproduce

1. Start with admin_token set
2. Create a user, and create an organization with that user
3. Navigate to /admin/ and attempt to delete the user

### Expected behaviour
It should be possible to delete this user, or at least prevent future logins somehow. Alternatively, users should be prevented from creating organizations.

### Actual behaviour
The user could not be deleted with the following error message:

> Error deleting user
> Can't delete last owner

### Relevant logs

```
[2020-03-28 23:08:43][request][INFO] POST /admin/users/<uuid>/delete
[2020-03-28 23:08:43][error][ERROR] Can't delete last owner
[2020-03-28 23:08:43][response][INFO] POST /admin/users/<uuid>/delete (delete_user) => 400 Bad Request
```

**Comment by dani-garcia** [comment]
Hmm, for this we need to do two things I think:
- When trying to delete a user that's the last owner from the admin page, we should detect the error and offer to also delete the organization. This could just be a dialog after the delete user confim dialog.

- On the other side, we should also allow one way to promote a different user to owner, in case we want to keep the organization in place. We can't make another user join, because that would require access for the crypto keys, but we can change a users organization level, probably by clicking on the organization name from the user entry in the admin page, we could show a dialog there to switch users level.

**Comment by jjlin** [comment]
It might make sense to do this by implementing the relevant pieces of the Bitwarden public API (https://docs.bitwarden.com/), which could be the foundation of a full implementation later on.

**Comment by speedygonzales391** [comment]
Any progrese about this?

**Comment by BlackDex** [comment]
I'm currently working on a way to change a user-type from the users/overview page.
That way you can at least promote an other user to admin if that user is already a member of that same organization.

And i'm adding a delete org on the organization overview page.

I find it tricky to offer a new dialog asking to delete the org also if that users is the last owner.
I'm afraid that people will quickly press yes, yes, yes even if we add extra `are you sure too` dialog boxes.
People just do not read. Therefore i will add it to the org overview where it will be clear to delete an org and not a user.
