### ISSUE TITLE
Enable user SSO access using OAuth

### ISSUE THREAD

**Issue by lkraider** [dani-garcia/bitwarden_rs#94]
Would like to manage the users by enabling an OAuth source like Google or a custom one like a Keycloak instance.

**Comment by dani-garcia** [comment]
I consider this to be outside the scope of the project, so I won't be implementing this. That said, if someone wants to implement it, i'll accept a PR as long as the implementation doesn't over-complicate the rest of the code.

**Comment by dani-garcia** [comment]
To keep the issue tracker more focused, I'm closing this issue in favor of the meta issue at #246.

**Comment by lukasmrtvy** [comment]
What about https://docs.rs/crate/oauth2/ ? (google,github, hope for generic oidc and keycloak)

**Comment by varac** [comment]
I'd be happy if Oauth/OpenIDConnect would be implemented because it's the main blocker from including it in https://openappstack.net/

**Comment by manuschillerdev** [comment]
I would love to have a shot at experimenting with https://github.com/ramosbugs/oauth2-rs and vaultwarden.
I have common knowledge about oauth2 but would need some general guidance in which parts of vaultwarden would be affected by implementing it.

@dani-garcia would you be able to give us some hints on where to begin? :)

**Comment by robocrax** [comment]
Anyone working on this or know a solution that is available?

**Comment by Avsynthe** [comment]
Bitwarden supports SSO via SAML 2.0 and OIDC. I actually self-hosted Vaultwarden on the premise that it did also.

This is absolutely a must-have for me. For now though I have to add yet another step when onboarding users to my self-hosted suite of services I grace my family and friends with haha

It looks like an attempt is already being made to implement OIDC at #2449

**Comment by BloodyIron** [comment]
My vote is for SAML! Bitwarden SAML SSO experience is awesome, it would be fabulous to have in Vaultwarden!

**Comment by FunctionDJ** [comment]
I think OAuth would be a much better idea than SAML if it's one or the other. I've tried implementing a SAML client and it was an absolute mess. Implementing an OAuth 2.1 client on the other hand was about 20 lines of code after i understood how it works.

**Comment by miglen** [comment]
Just to chime in, SAML or OAuth both would be awesome to have!

**Comment by luebke-dev** [comment]
OIDC pls

**Comment by wuast94** [comment]
would also love to see that, building a suite that contains many applications for friends and familys happens more and more, and it just makes sense to build arround SSO, im using authelia with Oauth for this. 
And the Bitwarden clients seems to have support for it. Would love to see that feature on the roadmap :)

**Comment by Avsynthe** [comment]
> would also love to see that, building a suite that contains many applications for friends and familys happens more and more, and it just makes sense to build arround SSO, im using authelia with Oauth for this. And the Bitwarden clients seems to have support for it. Would love to see that feature on the roadmap :)

Doing the exact same thing and would love this for the same reason. Though I've moved to authentik for this and replaced authelia and my old identity server. Much more robust and a single application! Also supports more SSO types like and OIDC, SAML rather than just Oauth and LDAP

**Comment by viperfan7** [comment]
Honestly I'm super surprised that vaultwarden doesn't support some form of SSO, like, say, I have keycloak set up as my SSO provider, and it supports OIDC quite well.

Adding my +1 for OIDC support

**Comment by samuelleb11** [comment]
Authentik user here 🙋‍♂️ Would love to see SSO !

**Comment by ihatenodejs** [comment]
Yet another Authentik user here, would love to see this implemented!

**Comment by Avsynthe** [comment]
You can follow the progress here: https://github.com/dani-garcia/vaultwarden/pull/3899

Just don't bump that thread. Leave it clear for them to work in. They're close

**Comment by HWiese1980** [comment]
PocketID user here, chiming in. You guys got my vote!

**Comment by MDeveloping** [comment]
SSO / LDAP would be very important for us and nice to see. In a first step a basic user / password authentication for LDAP Users would be enough. Users could be further managed inside of Vaultwarden.

In a second step, managing by LDAP Groups would be good.

**Comment by Datenschmutz** [comment]
+1 from another Authentik user

**Comment by hitmeet** [comment]
+1 from keycloak user. It would help a lot.

**Comment by SoFMeRight** [comment]
+1 (If this was implemented I'd actually feel reason to switch to vaultwarden from the official bitwarden container image.🙈) Zitadel user.

**Comment by justatechie** [comment]
+1 from a kanidm user!

**Comment by Blackcbears** [comment]
+1

**Comment by mortee** [comment]
+1

**Comment by FlattusBlastus** [comment]
https://developers.google.com/identity/openid-connect/openid-connect

erm??? Being your own IdP AND hosting your vault at the same time?

**Comment by Eirikr70** [comment]
Pocket-ID and TinyAuth user here. I would be fond of that additional layer!

**Comment by alfonsrv** [comment]
Let me release your expectations – OAuth or LDAP auth the way you imagine it is likely never to come to Vaultwarden. It's already been discussed for 5 years+ and lots of information is available throughout the internet as to why this is.

The main reason being the way Bitwarden handles en-/decryption and requires the master password, else the web interface would have to be rewritten completely, which @dani-garcia mentioned is out of scope at multiple occasions.

The regular Bitwarden handles this over Key Connector which (in easy terms) stores the master passwords and releases them to a user once they are sufficiently authenticated. Due to license restrictions of Key Connector this feature will likely never be implemented though (Timshel also outlined in the [PR mentioned here](https://github.com/dani-garcia/vaultwarden/pull/3899#:~:text=Bitwarden%20key%20connector%20is%20not%20supported%20and%20due%20to%20the%20license%20it%27s%20highly%20unlikely%20that%20it%20will%20ever%20be%3A) after I brought it up) – you'll need to purchase a subscription with Bitwarden if you want Enterprise Features. It's relatively inexpensive and helps move Bitwarden + open-source in general along.

**Comment by MDeveloping** [comment]
This is regrettable. As Vaultwarden doesn't support LDAP its completely useless for companies if more than a handful people want to use it.

It would make sense to extend the project far enough to allow for a proper LDAP implementation. As noted above, even an initial step of supporting LDAP username and password authentication would already be valuable, while keeping the rest of the administration within Vaultwarden.

There is a project called "vaultwarden-ldap", but unfortunately it only synchronizes LDAP users with Vaultwarden and does not provide LDAP authentication. Still, it might be worth looking into as a reference, since it already handles communication with LDAP.

**Comment by BlackDex** [comment]
> This is regrettable. As Vaultwarden doesn't support LDAP its completely useless for companies if more than a handful people want to use it.
> 
> It would make sense to extend the project far enough to allow for a proper LDAP implementation. As noted above, even an initial step of supporting LDAP username and password authentication would already be valuable, while keeping the rest of the administration within Vaultwarden.
> 
> There is a project called "vaultwarden-ldap", but unfortunately it only synchronizes LDAP users with Vaultwarden and does not provide LDAP authentication. Still, it might be worth looking into as a reference, since it already handles communication with LDAP.

@MDeveloping as far as i know we support LDAP in the sense that account creation can be automated via the [Directory Connector](https://bitwarden.com/help/directory-sync/). There isn't anything more we can do to be honest.

Using the password from LDAP or SSO is not how it works as a master password is always needed to encrypt/decrypt the stored data.

The only way to have this working via SSO is by implementing support for the [Key Connector](https://bitwarden.com/help/about-key-connector/) or maybe the new [Trusted Devices](https://bitwarden.com/help/about-trusted-devices/)

Also, i think you can run the key-connector locally without any issues, see https://github.com/bitwarden/key-connector.
But, Vaultwarden does not have any support for this. That the key-connector tool it self is Bitwarden Licensed doesn't mean you can't use it as far as i know. The same goes for the Directory Connector btw, that is also Bitwarden Licensed.

Someone just need to develop it.
