### ISSUE TITLE
Ansible playbook for raspberry pi

### ISSUE THREAD

**Issue by martient** [dani-garcia/bitwarden_rs#997]
Hi,
I have created an ansible playbook for my personal deployment of Bitwarden RS on my **raspberry pi 3B+**.

This installation used Docker to work with two service bitwardenrs: raspberry and Caddy, you can find all the information for use it on this repository: https://github.com/martient/bitwardenrs-ansible

Duration of the installation: **5-10 minutes**

**Comment by fbartels** [comment]
Hi @martient,

just a quick remark. Instead of telling users to modify the docker-compose.yml you could also get the changed values either from a .env file located from where you are running docker-compose or you could export these to the environment of the shell (so you could also set it directly with ansible if I am not mistaken).

**Comment by martient** [comment]
Hi @fbartels,
Thanks for your remark, I took it and do the modification tonight, it's clearly a better approach

**Comment by jjlin** [comment]
I've created a wiki page for indexing deployment examples: https://github.com/dani-garcia/bitwarden_rs/wiki/Deployment-examples

Feel free to edit that page and add a better summary of your example if you like. Please close this issue; it's not really an issue in the software.
